# Generated by Django 4.0.3 on 2022-03-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username',models.CharField(max_length=600)),
                ('name', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=6000)),
                ('city', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
    ]
