# Generated by Django 4.0.3 on 2022-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomplaint',
            name='username',
            field=models.CharField(max_length=4000),
        ),
    ]
