# Generated by Django 4.0.3 on 2022-04-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_addcomplaint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomplaint',
            name='mobile_no',
            field=models.IntegerField(default=6897568945, max_length=10),
            preserve_default=False,
        ),
    ]
