# Generated by Django 4.0.3 on 2022-04-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_addcomplaint_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomplaint',
            name='reported_date',
            field=models.CharField(default=21, max_length=10),
            preserve_default=False,
        ),
    ]
