# Generated by Django 4.0.3 on 2022-04-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_addcomplaint_reported_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcomplaint',
            name='reported_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
