# Generated by Django 4.0.3 on 2022-04-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_addcomplaint_reported_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcomplaint',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Progress'), (3, 'Close')], default=1),
        ),
        migrations.AlterField(
            model_name='addcomplaint',
            name='category',
            field=models.IntegerField(choices=[(1, 'Accident'), (2, 'Fraud'), (3, 'Robbery'), (4, 'Missing'), (5, 'Cyber Crime'), (6, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='addcomplaint',
            name='description',
            field=models.CharField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='addcomplaint',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
